### ISSUE TITLE
Issue with font & readability

### ISSUE THREAD

**Issue by KonradYerba** [Mossy1022/Smart-Connections-Visualizer#10]
Hey, great great plugin! Loving it. 

One big problem I have though, is that the titles of notes or sections in the smart connections graph, show up as super unreadable...blurry. I have to zoom in close to see what's written, and then it loses its purpose. I tried changing the text threshold, but the problem is the same. I think it's because the note title text has a weird font and a shadow, which you cannot adjust.

Any suggestions?

**Comment by karenwky** [comment]
Agree, and the text color is unreadable in light theme. I suggest reference to the native graph view to change color according to color scheme setting.

**Comment by Mossy1022** [comment]
So sorry for the delay! And thanks you two.  I'll update it to be a font more friendly for all themes.  I use dark so I never noticed.  I'll have a new release out very soon and update you.

**Comment by Mossy1022** [comment]
1.0.15 is available.  Let me know how it looks!

**Comment by karenwky** [comment]
Wow it is so much better now and perfect to read for both color schemes! Thank you so much for the update! :D

**Comment by Mossy1022** [comment]
Glad to hear! Thanks for the feedback :)
