### ISSUE TITLE
Plugin Changing Obisdian Theme

### ISSUE THREAD

**Issue by marblagin** [Mossy1022/Smart-Connections-Visualizer#4]
Hi there, I love the concept of this plugin as I use Smart Connections alot but would it possible to remove the theme it comes with it? The plugin is changing my Obsidian theme when I enable it. I am sure many other folks would like to still to their theme as well and just use the plugin for its purpose, the visualizer

**Comment by Mossy1022** [comment]
Thanks for the catch! I have just removed it in the latest release :) Let me know if that resolved your issue.

**Comment by marblagin** [comment]
Thank you! Looks like version 1.0.10 is failing to install though. Tried restarting obsidian, and removing and reinstalling the plugin, still battling to install.

**Comment by Mossy1022** [comment]
Interesting, I will take a look.

**Comment by Mossy1022** [comment]
@marblagin Found the issue.  I just pushed the new release and you should be good to go!  Still replaced version 1.0.10 as not all the binaries were included.

**Comment by marblagin** [comment]
Awesome thank you! All is working and the plugin is great!!
