### ISSUE TITLE
Conflict with Excalidraw

### ISSUE THREAD

**Issue by Cossackx** [Mossy1022/Smart-Connections-Visualizer#5]
The addon now conflicts with Excalidraw and won't let draw on its canvas.

Any ideas how to fix?

**Comment by mossy426** [comment]
@Cossackx Thanks for the lookout! I've pushed a fix.  Let me know if this is now resolved for you.

**Comment by Mossy1022** [comment]
@Cossackx Thanks for the lookout! I've pushed a fix. Let me know if this is now resolved for you.

**Comment by Cossackx** [comment]
> @Cossackx Thanks for the lookout! I've pushed a fix. I needed to scope some of my variables to be more specific to this plugin. Let me know if this is now resolved for you.

will test now

**Comment by Mossy1022** [comment]
@Cossackx  Going to close this soon as it should be resolved, but let me know if not :)

**Comment by Cossackx** [comment]
> @Cossackx Going to close this soon as it should be resolved, but let me know if not :)

Still conflicting. Had to shut off vizualizer

**Comment by mossy426** [comment]
Ok can you elaborate more?  I saw that it was making the hamburger menu from excalidraw not clickable so you couldn't use it.  From the screenshot, you can see I can open the menu + draw on excalidraw.  Are you using the most up to date version?

<img width="1131" alt="Screenshot 2024-06-27 at 5 19 48 PM" src="https://github.com/Mossy1022/Smart-Connections-Visualizer/assets/80353770/640df4fc-6e09-4597-aec3-c67dc3068657">

**Comment by Cossackx** [comment]
![image](https://github.com/Mossy1022/Smart-Connections-Visualizer/assets/121278003/66a6a03a-8565-4fa1-b095-3b2d7c19627a)

**Comment by Mossy1022** [comment]
Appreciate the info @Cossackx.   I can't seem to replicate the bug, but I'm creating a new release that I expect out by tomorrow with a lot of changes under the hood.  It should address any and all conflicts with other functionality outside the plugin.

**Comment by Mossy1022** [comment]
@Cossackx Ok nevermind, I was able to finish it much faster than I thought. 

Please let them know that they can update to v1.0.12 and it shouldn't interfere with anything.  Thanks! 😁

**Comment by Mossy1022** [comment]
Since I haven't seen any other issues or users experiencing this since the last release, I will be closing this soon unless you're still reporting the same issue.  I'll give it some more time 👍🏻
