### ISSUE TITLE
Plugin ID mistmatch

### ISSUE THREAD

**Issue by cristianvasquez** [Mossy1022/Smart-Connections-Visualizer#6]
Hi!, 

I'm giving a try to plugin, but Obsidian fails to install it. It says: `plugin ID mistmatch`

**Comment by AMGMNPLK** [comment]
I got the same trying to update. Then I uninstalled, tried to install and got the same error.

**Comment by mossy426** [comment]
Got it, just pushed a fix for an excalidraw update.  Will push in a few minutes this fix.

**Comment by Mossy1022** [comment]
@AMGMNPLK @cristianvasquez  Got it! Pushed a fix for an issue and there was a conflict with a binary.  This should be resolved.  Let me know if you're still experiencing any issues.

**Comment by Mossy1022** [comment]
Going to close this soon as this should be resolved, but let me know if it's not :)
