### ISSUE TITLE
Error "No nodes or links to display after filtering. Adjust filter settings"

### ISSUE THREAD

**Issue by Fffrankoo** [Mossy1022/Smart-Connections-Visualizer#7]
After clicking the Open Smart Connections Visualizer icon, I get the above error message and the Smart Connections Visualizer window remains empty. How can I adjust the filter settings?
(I am using the latest version of the Smart Connections plugin available for the supporter community.)
Thank you for your help!
Frankooo

**Comment by Fffrankoo** [comment]
Found the explanatory video on https://www.youtube.com/watch?v=dbFRyJBkxS0
Issue solved!

**Comment by mossy426** [comment]
Glad you found it :) I should just include a link to in in the readme.  Thanks for the lookout!
