### ISSUE TITLE
Some usability issues if smart connections graph is pinned in sidebar

### ISSUE THREAD

**Issue by AW2307** [Mossy1022/Smart-Connections-Visualizer#8]
Hi,

it's hard to overstate how enthusiastic I am about this plugin. Looking forward to its tremendous potential being realized over time, on top of an already GREAT first version!

There are some usability flaws right now if the plugin is pinned in the right side bar. All of these were **only observed if plugin is pinned in side bar**, rather than being used in a normal tab.

See screenshot for clarity on my setup.

![Screenshot 2024-07-27 at 17 57 14](https://github.com/user-attachments/assets/cd7c5eed-fe7c-482a-ad47-e87ec3f9be56)

**Recurring unexpected alerts**

Anytime I access any note with any filter set, it will unexpectedly display the "no nodes to display after filtering" message, even though nodes are actually being displayed. Furthermore, this alert is shown four times instead of once.

If I instead close the tab with the smart connections graph, navigate to a different note, and then reopen the graph via the button in the ribbon, no messages are displayed (as expected).

**Unresponsive menu buttons**

The "Filters", "Display" and "Forces" buttons become unresponsive after switching to a different note and then reopening the plugin's settings menu.

**Settings not retained**
If the pinned tab is closed and the smart connections graph is then reopened via the ribbons button, then previously applied filter settings are not retained. Filters appear to reset to the default settings in this case.

Thanks for looking into these observations, and pls keep up the incredible work!

**Comment by Mossy1022** [comment]
@AW2307 Thank you so much for support and feedback!  I'll be fixing these up soon.  I'm out on vacation for the week, but will make some time to get to this asap 😁

**Comment by Mossy1022** [comment]
@AW2307 So sorry for the delay.  Just got back from a longer vacation thank expected 😅  Please update to version 1.0.13 to see which issues this resolves.  It appears the code being executed when the view isn't visible was the culprit.  Let me know!

**Comment by AW2307** [comment]
Hey @Mossy1022 

sounds like you had a good time 😉

I can confirm that all of the issues previously observed seem to have been addressed through these fixes.

Thank you!
