### ISSUE TITLE
Not sure why it's blank after I installed

### ISSUE THREAD

**Issue by tamdrashtri** [Mossy1022/Smart-Connections-Visualizer#9]
Hello Evan,

I'm not sure why after I installed the plugin, the graph does not have any connections at all. I've checked all the requirements 

![CleanShot 2024-08-17 at 17 43 09](https://github.com/user-attachments/assets/b958ecaf-f9be-449e-b868-cab1823ddde2)

**Comment by ottantaventi** [comment]
This happens to me as well.

![image](https://github.com/user-attachments/assets/d7883082-3d55-4595-9b47-7846e8df1a56)

**Comment by Mossy1022** [comment]
Hey Guys!  I'm looking in to it.  Updates to the Smart Connections plugin can affect this companion plugin, so I'm checking with the developer to see what's changed.

**Comment by Mossy1022** [comment]
@tamdrashtri @ottantaventi  Yes it appears it was an update with the SC plugin that I needed to update a variable for. Thanks for the look out 😁 Please update to the latest version (1.0.14) and let me know if that resolves your issue.

**Comment by ottantaventi** [comment]
It works now:
![image](https://github.com/user-attachments/assets/8eb868b9-394d-44ec-ade9-5b7f46d86daf)

May I suggest to improve the readability of the notes names in the graph ?

Thanks in advance for the your great work !

**Comment by Mossy1022** [comment]
@ottantaventi Great, thanks for the suggestion!  I haven't explored looking at the text through all the different themes and can see it's not great with yours.  I'll use a different font then.

**Comment by tamdrashtri** [comment]
Thank you! I can see it now 😇 The font is just a bit off!
